### ISSUE TITLE
Gmsh lines

### ISSUE THREAD

**Issue by bjaraujo** [jonathanlambrechts/qgis-gmsh#2]
Why are gmsh lines written as a line loop?

Line(IL+0) = {IP+0, IP+1, IP+2, IP+3, IP+4, IP+5, IP+6, IP+7, IP+8, IP+9, IP+10, IP+11, IP+12, IP+13, IP+14, IP+15, IP+16, IP+17, IP+18, IP+19, IP+20, IP+21, IP+22, IP+23, IP+24, IP+25, IP+26, IP+27, IP+28, IP+29, IP+30, IP+31, IP+32, IP+33, IP+0};

I think in gmsh lines should only have 2 points and then the lineloop connects the line ids. In this way I could do boundary constrained mesh generation.

Is there a way I can force line segments to have only 2 points?

Thanks for making available this plugin for QGIS. It seems a very good addition to QGIS.

**Comment by jonathanlambrechts** [comment]
Each entity is written as a single Line in the Geo point, this allows to generate a mesh coarser than the geometry and prevent to force each point of the geomety to be present in the 1D mesh.
The plugin is not designed to force the 1D mesh. If you want some points to be present in the mesh, you can use shapefiles composed of lines instead of polygons and split the lines into different "features" (i.e. lines) at the points you want to force. Here is an example where 2 points are forced and 2 are not.
[split_line_example.zip](https://github.com/ccorail/qgis-gmsh/files/284097/split_line_example.zip)
If you really need it, I can easily add an option to force all points to be in the 1D mesh (by using only lines composed of one single segment, the way you describe it).

**Comment by bjaraujo** [comment]
@ccorail 

Sounds good. Will give it a try.

**Comment by jonathanlambrechts** [comment]
I just did a commit that add an option to force all boundary points, can you try the github version of the plugin ? If it works for you, I will push it to the QGIS plugin respository.

**Comment by bjaraujo** [comment]
@ccorail 

Hi,

I tested it and looks good. Thanks very much.

![test3_geo](https://cloud.githubusercontent.com/assets/5067963/15574856/9c9ed646-2347-11e6-8587-7cfbd4507682.png)
![test3_mesh](https://cloud.githubusercontent.com/assets/5067963/15574861/a29cf41a-2347-11e6-9fa0-079a912a1d15.png)
